server:
  port: 8080
  #  servlet:
  #    context-path: /essplatform
  context-path: /essplatform
mybatis:
  #mybatis的xml文件配置 没有此项配置则为注解模式
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.chen.entity
spring:
  #mysql数据源配置 119.45.7.196  81.70.43.116
#  datasource:
#    username: root
#    password: n5*zsqENI&
#    url: jdbc:mysql://119.45.7.196:3306/essplatform?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&amp
#    driver-class-name: com.mysql.cj.jdbc.Driver
  #达梦数据源配置  192.168.1.105
  datasource:
    username: CLT
    password: qwe123!@#
    url: jdbc:dm://10.192.81.21:5236/CLTESS
    driver-class-name: dm.jdbc.driver.DmDriver
  #人大金仓数据源配置
  #  datasource:
  #    username: CLTESS
  #    password: CLTESS1234
  #    url: jdbc:kingbase8://192.168.1.109:54321/CLTESS
  #    driver-class-name: com.kingbase8.Driver
  #神舟通用数据源配置
#    datasource:
#      username: cltess
#      password: S&qRD4ZN5xTX
#      url: jdbc:oscar://localhost:2003/ESSPLATFORM
#      driver-class-name: com.oscar.Driver
#  tomcat:
#    #连接池同一时间可分配的最大活跃连接数
#    maxActive: 150
#    #始终保留在池中的最大连接数，如果启用，将定期检查限制连接，
#    #超出此属性设定的值且空闲时间超过minEvictableIdleTimeMillis的连接则释放
#    max-idle: 150
#    #始终保留在池中的最小连接数，池中的连接数量若低于此值则创建新的连接，如果连接验证失败将缩小至此值
#    minIdle: 10
#    #连接池启动时创建的初始连接数量
#    initialSize: 10
#    #最大等待时间（毫秒），如果在没有连接可用的情况下等待超过此时间，则抛出异常 300s
#    maxWait: 300000
  aop:
    proxy-target-class: true
    auto: true
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    #    servlet:
    content-type: text/html
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${myConfig.pdfPath}
  devtools:
    restart:
      #需要实时更新的目录
      additional-paths: resources/**,static/**,templates/**
      enabled: false
  #   spring 2.1写法   #
  #  servlet:
  #    multipart:
  #      max-file-size: 1024MB
  #      max-request-size: 1024MB
  #  spring 1.5写法    #
  http:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  cache:
    ehcache:
      config: ehcache.xml
# slf4j日志配置
logging:
  # 配置级别
  level:
    com.chen.dao.SealMapper: debug
    com.chen.dao.ApplyMapper: debug
    #分包配置级别，即不同的目录下可以使用不同的级别
    root: info
  # 指定输出日志的文件名，默认输出至当前项目目录下
#  file: D:/essplatform.log
#    thymeleaf:
#      cache: false
#      prefix: classpath:/templates/
#      suffix: .html
#      encoding: UTF-8
#      content-type: text/html
#      mode: HTML5
myConfig:
  #  tempFilepath: D:\temp\attachment\    152.136.123.210  123.207.220.137
  tempFilepath: /usr/ESSTEMP/attachment/
  hostURL: http://10.192.81.21:8088
  socketIP: 10.192.81.21
  fileTypePath: /opt/esstempfile/jurFile.txt
  #使用的加密方式：1加密机，0token
  securityType: 1